<?php

namespace Database\Seeders;

use App\Enums\Role;
use App\Models\Hotel;
use App\Models\User;
use Illuminate\Database\Seeder;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = User::where('role', 'vendor')->get();
        if ($vendors->isEmpty()) {
            return;
        }

        $hotels = [
            [
                'vendor_id' => $vendors->get(0)->id,
                'name' => 'Grand Plaza Hotel',
                'description' => 'Luxury 5-star hotel in the heart of the city with stunning views and premium amenities.',
                'address' => '123 Main Street',
                'city' => 'New York',
                'country' => 'USA',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(0)->id,
                'name' => 'Seaside Resort & Spa',
                'description' => 'Beachfront resort with spa, pool, and direct beach access.',
                'address' => '456 Ocean Drive',
                'city' => 'Miami',
                'country' => 'USA',
                'latitude' => 25.7617,
                'longitude' => -80.1918,
                'check_in' => '14:00:00',
                'check_out' => '12:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(0)->id,
                'name' => 'Mountain View Lodge',
                'description' => 'Cozy lodge with mountain views, fireplace lounges, and hiking trails.',
                'address' => '789 Pine Road',
                'city' => 'Denver',
                'country' => 'USA',
                'latitude' => 39.7392,
                'longitude' => -104.9903,
                'check_in' => '16:00:00',
                'check_out' => '10:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(1)->id,
                'name' => 'Urban Boutique Hotel',
                'description' => 'Modern boutique hotel with contemporary design and personalized service.',
                'address' => '321 Fashion Avenue',
                'city' => 'Los Angeles',
                'country' => 'USA',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(1)->id,
                'name' => 'Historic Inn & Suites',
                'description' => 'Charming historic inn with vintage decor and modern comforts.',
                'address' => '55 Heritage Lane',
                'city' => 'Boston',
                'country' => 'USA',
                'latitude' => 42.3601,
                'longitude' => -71.0589,
                'check_in' => '16:00:00',
                'check_out' => '12:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(2)->id,
                'name' => 'Desert Oasis Resort',
                'description' => 'Luxury desert resort with golf course, spa, and stunning sunset views.',
                'address' => '888 Dune Drive',
                'city' => 'Phoenix',
                'country' => 'USA',
                'latitude' => 33.4484,
                'longitude' => -112.0740,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(2)->id,
                'name' => 'Lakeside Retreat',
                'description' => 'Peaceful lakeside hotel with water sports and nature activities.',
                'address' => '42 Lake Shore Drive',
                'city' => 'Chicago',
                'country' => 'USA',
                'latitude' => 41.8781,
                'longitude' => -87.6298,
                'check_in' => '14:00:00',
                'check_out' => '10:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(3)->id,
                'name' => 'Airport Transit Hotel',
                'description' => 'Convenient airport hotel with shuttle service and business facilities.',
                'address' => '1 Terminal Road',
                'city' => 'Atlanta',
                'country' => 'USA',
                'latitude' => 33.6407,
                'longitude' => -84.4277,
                'check_in' => '12:00:00',
                'check_out' => '12:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(3)->id,
                'name' => 'Wine Country Inn',
                'description' => 'Elegant inn nestled in vineyards with wine tasting and gourmet dining.',
                'address' => '777 Vineyard Way',
                'city' => 'Napa',
                'country' => 'USA',
                'latitude' => 38.2975,
                'longitude' => -122.2869,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(4)->id,
                'name' => 'Coastal Cliff Hotel',
                'description' => 'Dramatic cliff-top hotel with ocean views and fine dining.',
                'address' => '100 Cliffside Boulevard',
                'city' => 'San Francisco',
                'country' => 'USA',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'check_in' => '16:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(4)->id,
                'name' => 'Forest Cabin Resort',
                'description' => 'Rustic cabins in the forest with hiking trails and wildlife viewing.',
                'address' => '200 Wilderness Trail',
                'city' => 'Portland',
                'country' => 'USA',
                'latitude' => 45.5152,
                'longitude' => -122.6784,
                'check_in' => '15:00:00',
                'check_out' => '10:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(0)->id,
                'name' => 'City Center Marriott',
                'description' => 'Modern business hotel with conference facilities and rooftop bar.',
                'address' => '500 Business Plaza',
                'city' => 'Houston',
                'country' => 'USA',
                'latitude' => 29.7604,
                'longitude' => -95.3698,
                'check_in' => '15:00:00',
                'check_out' => '12:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(1)->id,
                'name' => 'Tropical Paradise Resort',
                'description' => 'All-inclusive tropical resort with private beach and water park.',
                'address' => '333 Paradise Island',
                'city' => 'Orlando',
                'country' => 'USA',
                'latitude' => 28.5383,
                'longitude' => -81.3792,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(2)->id,
                'name' => 'Ski Lodge Chalet',
                'description' => 'Luxury ski-in/ski-out lodge with spa and après-ski bar.',
                'address' => '999 Mountain Peak',
                'city' => 'Aspen',
                'country' => 'USA',
                'latitude' => 39.1911,
                'longitude' => -106.8175,
                'check_in' => '16:00:00',
                'check_out' => '10:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(3)->id,
                'name' => 'Riverfront Hotel',
                'description' => 'Scenic riverside hotel with boat tours and fishing excursions.',
                'address' => '150 River Walk',
                'city' => 'New Orleans',
                'country' => 'USA',
                'latitude' => 29.9511,
                'longitude' => -90.0715,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(4)->id,
                'name' => 'Garden Villa Hotel',
                'description' => 'Tranquil hotel surrounded by botanical gardens and meditation spaces.',
                'address' => '88 Garden Path',
                'city' => 'Seattle',
                'country' => 'USA',
                'latitude' => 47.6062,
                'longitude' => -122.3321,
                'check_in' => '14:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(0)->id,
                'name' => 'Tech Hub Hotel',
                'description' => 'Modern hotel with smart rooms, co-working space, and tech amenities.',
                'address' => '250 Innovation Drive',
                'city' => 'Austin',
                'country' => 'USA',
                'latitude' => 30.2672,
                'longitude' => -97.7431,
                'check_in' => '15:00:00',
                'check_out' => '11:00:00',
                'status' => 'active',
            ],
            [
                'vendor_id' => $vendors->get(1)->id,
                'name' => 'Historic Downtown Hotel',
                'description' => 'Restored 1920s hotel with vintage charm and modern amenities.',
                'address' => '75 Heritage Square',
                'city' => 'Charleston',
                'country' => 'USA',
                'latitude' => 32.7765,
                'longitude' => -79.9311,
                'check_in' => '16:00:00',
                'check_out' => '12:00:00',
                'status' => 'active',
            ],
        ];

        foreach ($hotels as $data) {
            Hotel::firstOrCreate(
                ['name' => $data['name'], 'vendor_id' => $data['vendor_id']],
                $data
            );
        }
    }
}
